#!/usr/bin/env python3
"""
Paper-style final comparison plots for Track-A evaluation.

Inputs
------
A comparison directory generated by:

    python baseline/NDTVS/ndtvs_analysis.py compare \
        <proposed_eval_dir> \
        <hppo_rsu_eval_dir> \
        <ndtvs_eval_dir> \
        --out <comparison_dir>

Expected files
--------------
<comparison_dir>/means.csv
<comparison_dir>/paired_differences.csv
<comparison_dir>/comparison.json

Outputs
-------
<output_dir>/final_performance_comparison.png
<output_dir>/final_performance_comparison.pdf
<output_dir>/paired_difference_ci.png
<output_dir>/paired_difference_ci.pdf
<output_dir>/plot_manifest.json

Notes
-----
- This script does not modify evaluation results.
- Bars show the 30-scenario mean from means.csv.
- This script intentionally does NOT fabricate per-method confidence intervals,
  because means.csv contains only means.
- Paired 95% bootstrap CIs already produced by ndtvs_analysis.py are shown in
  a separate paired-difference figure.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import tempfile
from pathlib import Path

import numpy as np


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def pretty_algorithm(name: str) -> str:
    mapping = {
        "ndtvs": "NDTVS",
        "hppo_rsu": "HPPO-RSU",
        "proposed": "Proposed",
    }
    return mapping.get(name, name)


METRICS = [
    {
        "key": "qoe_surrogate_per_user_slot",
        "title": "QoE Surrogate",
        "ylabel": "QoE / user-slot",
        "higher_better": True,
    },
    {
        "key": "average_quality_utility",
        "title": "Average Quality Utility",
        "ylabel": "Utility / delivered chunk",
        "higher_better": True,
    },
    {
        "key": "stall_ratio",
        "title": "Stall Ratio",
        "ylabel": "Stalled user-slots / all user-slots",
        "higher_better": False,
    },
    {
        "key": "request_failure_ratio",
        "title": "Request Failure Ratio",
        "ylabel": "Failed requests / all requests",
        "higher_better": False,
    },
    {
        "key": "delivered_chunks_per_user_slot",
        "title": "Delivered Chunks",
        "ylabel": "Chunks / user-slot",
        "higher_better": True,
    },
    {
        "key": "dpp_cost_per_user_slot",
        "title": "DPP Cost",
        "ylabel": "DPP cost / user-slot",
        "higher_better": False,
    },
    {
        "key": "hire_rate",
        "title": "UAV Hiring Rate",
        "ylabel": "Hired UAV-frames / UAV-frames",
        "higher_better": None,
    },
    {
        "key": "energy_consumed_j",
        "title": "UAV Energy Consumption",
        "ylabel": "Energy / episode [J]",
        "higher_better": None,
    },
]


def require_columns(
    rows: list[dict[str, str]],
    columns: list[str],
    source: Path,
) -> None:
    if not rows:
        raise ValueError(f"No rows in {source}")

    missing = [
        column
        for column in columns
        if column not in rows[0]
    ]

    if missing:
        raise ValueError(
            f"Missing columns in {source}: {missing}"
        )


def load_means(path: Path) -> tuple[list[str], dict[str, dict[str, float]]]:
    rows = read_csv(path)

    required = ["algorithm", "episodes"] + [
        metric["key"] for metric in METRICS
    ]
    require_columns(rows, required, path)

    preferred_order = ["ndtvs", "hppo_rsu", "proposed"]

    available = [row["algorithm"] for row in rows]
    algorithms = [
        name
        for name in preferred_order
        if name in available
    ]

    algorithms += [
        name
        for name in available
        if name not in algorithms
    ]

    values: dict[str, dict[str, float]] = {}

    for row in rows:
        algorithm = row["algorithm"]

        values[algorithm] = {
            "episodes": float(row["episodes"]),
        }

        for metric in METRICS:
            values[algorithm][metric["key"]] = float(
                row[metric["key"]]
            )

    return algorithms, values


def load_pairs(path: Path) -> list[dict[str, object]]:
    rows = read_csv(path)

    require_columns(
        rows,
        [
            "difference",
            "metric",
            "mean",
            "ci95_low",
            "ci95_high",
        ],
        path,
    )

    parsed: list[dict[str, object]] = []

    for row in rows:
        low = (
            float(row["ci95_low"])
            if row["ci95_low"] not in ("", "None", "null")
            else math.nan
        )
        high = (
            float(row["ci95_high"])
            if row["ci95_high"] not in ("", "None", "null")
            else math.nan
        )

        parsed.append(
            {
                "difference": row["difference"],
                "metric": row["metric"],
                "mean": float(row["mean"]),
                "ci95_low": low,
                "ci95_high": high,
            }
        )

    return parsed


def configure_matplotlib():
    os.environ.setdefault(
        "MPLCONFIGDIR",
        str(Path(tempfile.gettempdir()) / "trackA_final_plot_mpl"),
    )

    import matplotlib

    matplotlib.use("Agg")

    import matplotlib.pyplot as plt

    plt.rcParams.update(
        {
            "font.size": 10,
            "axes.titlesize": 10.5,
            "axes.labelsize": 9.5,
            "legend.fontsize": 9,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.grid": True,
            "grid.alpha": 0.18,
            "figure.facecolor": "white",
            "savefig.facecolor": "white",
        }
    )

    return plt


def scientific_if_needed(ax, values: np.ndarray) -> None:
    finite = values[np.isfinite(values)]

    if finite.size == 0:
        return

    max_abs = float(np.max(np.abs(finite)))

    if max_abs >= 1e4 or (
        0 < max_abs < 1e-3
    ):
        ax.ticklabel_format(
            axis="y",
            style="sci",
            scilimits=(-2, 3),
        )


def add_value_labels(ax, bars, values: np.ndarray) -> None:
    finite = values[np.isfinite(values)]

    if finite.size == 0:
        return

    spread = max(
        float(np.max(finite) - np.min(finite)),
        float(np.max(np.abs(finite))),
        1e-12,
    )

    offset = 0.018 * spread

    for bar, value in zip(bars, values):
        if not np.isfinite(value):
            continue

        if abs(value) >= 1000:
            text = f"{value:.2e}"
        elif abs(value) >= 10:
            text = f"{value:.2f}"
        elif abs(value) >= 1:
            text = f"{value:.3f}"
        else:
            text = f"{value:.4f}"

        y = value + offset if value >= 0 else value - offset

        ax.text(
            bar.get_x() + bar.get_width() / 2,
            y,
            text,
            ha="center",
            va="bottom" if value >= 0 else "top",
            fontsize=7.5,
            rotation=0,
        )


def plot_main(
    algorithms: list[str],
    values: dict[str, dict[str, float]],
    output_dir: Path,
    dpi: int,
) -> None:
    plt = configure_matplotlib()

    fig, axes = plt.subplots(
        2,
        4,
        figsize=(15.2, 7.2),
        layout="constrained",
    )

    x = np.arange(len(algorithms))
    labels = [pretty_algorithm(x) for x in algorithms]

    # Fixed plotting order only. The data itself is untouched.
    hatch_patterns = ["", "//", ".."]

    for ax, metric in zip(axes.flat, METRICS):
        key = metric["key"]

        y = np.asarray(
            [values[a][key] for a in algorithms],
            dtype=float,
        )

        bars = ax.bar(
            x,
            y,
            width=0.62,
            edgecolor="black",
            linewidth=0.7,
        )

        for i, bar in enumerate(bars):
            bar.set_hatch(
                hatch_patterns[i % len(hatch_patterns)]
            )

        ax.axhline(
            0.0,
            linewidth=0.7,
            alpha=0.55,
        )

        ax.set_xticks(x)
        ax.set_xticklabels(labels)
        ax.set_title(metric["title"])
        ax.set_ylabel(metric["ylabel"])

        if key in (
            "stall_ratio",
            "request_failure_ratio",
            "hire_rate",
        ):
            # All are physical ratios. Do not offset/zoom them.
            ymax = max(
                1e-12,
                float(np.nanmax(y)),
            )

            if ymax <= 1.0:
                ax.set_ylim(
                    0.0,
                    min(
                        1.0,
                        max(0.05, 1.18 * ymax),
                    ),
                )

        scientific_if_needed(ax, y)
        add_value_labels(ax, bars, y)

    fig.suptitle(
        "Performance Comparison on Paired Held-out Test Scenarios",
        fontsize=14,
    )

    fig.savefig(
        output_dir / "final_performance_comparison.png",
        dpi=dpi,
        bbox_inches="tight",
    )
    fig.savefig(
        output_dir / "final_performance_comparison.pdf",
        bbox_inches="tight",
    )

    plt.close(fig)


def pretty_difference(text: str) -> str:
    if " - " not in text:
        return text

    left, right = text.split(" - ", 1)

    return (
        f"{pretty_algorithm(left)} − "
        f"{pretty_algorithm(right)}"
    )


def plot_paired_ci(
    pairs: list[dict[str, object]],
    output_dir: Path,
    dpi: int,
) -> None:
    plt = configure_matplotlib()

    # Six performance metrics are most interpretable for a compact
    # paired-difference figure. Hiring/energy are retained in the CSV
    # and main panel.
    metric_keys = [
        "qoe_surrogate_per_user_slot",
        "average_quality_utility",
        "stall_ratio",
        "request_failure_ratio",
        "delivered_chunks_per_user_slot",
        "dpp_cost_per_user_slot",
    ]

    metric_titles = {
        metric["key"]: metric["title"]
        for metric in METRICS
    }

    differences = []
    for row in pairs:
        name = str(row["difference"])
        if name not in differences:
            differences.append(name)

    fig, axes = plt.subplots(
        2,
        3,
        figsize=(13.5, 7.0),
        layout="constrained",
    )

    for ax, metric in zip(axes.flat, metric_keys):
        subset = [
            row
            for row in pairs
            if row["metric"] == metric
        ]

        # Preserve compare() output order.
        labels = [
            pretty_difference(str(row["difference"]))
            for row in subset
        ]

        means = np.asarray(
            [float(row["mean"]) for row in subset],
            dtype=float,
        )
        lows = np.asarray(
            [float(row["ci95_low"]) for row in subset],
            dtype=float,
        )
        highs = np.asarray(
            [float(row["ci95_high"]) for row in subset],
            dtype=float,
        )

        y = np.arange(len(subset))

        finite_ci = (
            np.isfinite(lows)
            & np.isfinite(highs)
            & np.isfinite(means)
        )

        for i in range(len(subset)):
            if finite_ci[i]:
                lower = means[i] - lows[i]
                upper = highs[i] - means[i]

                ax.errorbar(
                    means[i],
                    y[i],
                    xerr=np.asarray(
                        [[lower], [upper]]
                    ),
                    fmt="o",
                    capsize=3,
                    linewidth=1.2,
                )
            else:
                ax.plot(
                    means[i],
                    y[i],
                    "o",
                )

        ax.axvline(
            0.0,
            linestyle="--",
            linewidth=1.0,
            alpha=0.75,
        )

        ax.set_yticks(y)
        ax.set_yticklabels(labels)
        ax.invert_yaxis()

        ax.set_title(metric_titles[metric])
        ax.set_xlabel("Paired mean difference (95% bootstrap CI)")

    fig.suptitle(
        "Paired Test-Scenario Differences",
        fontsize=14,
    )

    fig.savefig(
        output_dir / "paired_difference_ci.png",
        dpi=dpi,
        bbox_inches="tight",
    )
    fig.savefig(
        output_dir / "paired_difference_ci.pdf",
        bbox_inches="tight",
    )

    plt.close(fig)


def write_manifest(
    comparison_dir: Path,
    output_dir: Path,
    algorithms: list[str],
    values: dict[str, dict[str, float]],
) -> None:
    provenance_path = comparison_dir / "comparison.json"

    provenance = {}
    if provenance_path.is_file():
        provenance = json.loads(
            provenance_path.read_text(encoding="utf-8")
        )

    manifest = {
        "comparison_dir": str(comparison_dir.resolve()),
        "algorithms": algorithms,
        "display_algorithms": [
            pretty_algorithm(a)
            for a in algorithms
        ],
        "test_episodes": {
            a: int(values[a]["episodes"])
            for a in algorithms
        },
        "source_comparison_json": (
            str(provenance_path.resolve())
            if provenance_path.is_file()
            else None
        ),
        "same_selected_training_episode": provenance.get(
            "same_selected_training_episode"
        ),
        "selected_checkpoint_training_episodes": provenance.get(
            "selected_checkpoint_training_episodes"
        ),
        "note": (
            "Main bars are means over paired final test scenarios. "
            "The CI figure uses paired bootstrap intervals produced by "
            "ndtvs_analysis.py compare. Intervals quantify test-scenario "
            "variation conditional on the selected trained checkpoints, "
            "not training-seed uncertainty."
        ),
    }

    (output_dir / "plot_manifest.json").write_text(
        json.dumps(
            manifest,
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
    )
    parser.add_argument(
        "comparison_dir",
        type=Path,
        help=(
            "Directory containing means.csv, "
            "paired_differences.csv and comparison.json"
        ),
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help=(
            "Output directory. "
            "Default: <comparison_dir>/plots"
        ),
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=220,
    )

    args = parser.parse_args()

    if not 80 <= args.dpi <= 600:
        parser.error("--dpi must be between 80 and 600")

    comparison_dir = args.comparison_dir.resolve()

    means_path = comparison_dir / "means.csv"
    pairs_path = comparison_dir / "paired_differences.csv"

    if not means_path.is_file():
        parser.error(
            f"means.csv not found: {means_path}"
        )

    if not pairs_path.is_file():
        parser.error(
            f"paired_differences.csv not found: {pairs_path}"
        )

    output_dir = (
        args.out.resolve()
        if args.out is not None
        else comparison_dir / "plots"
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    algorithms, values = load_means(means_path)
    pairs = load_pairs(pairs_path)

    if len(algorithms) < 2:
        raise ValueError(
            "At least two algorithms are required"
        )

    plot_main(
        algorithms,
        values,
        output_dir,
        args.dpi,
    )

    plot_paired_ci(
        pairs,
        output_dir,
        args.dpi,
    )

    write_manifest(
        comparison_dir,
        output_dir,
        algorithms,
        values,
    )

    print("[OK] plots written to:")
    print(output_dir)

    for name in (
        "final_performance_comparison.png",
        "final_performance_comparison.pdf",
        "paired_difference_ci.png",
        "paired_difference_ci.pdf",
        "plot_manifest.json",
    ):
        print(" -", output_dir / name)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())